name: Release

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python
